server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
#      url: jdbc:mysql://180.76.245.161:3306/datamgrsys?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
#      username: root
#      password: MengTong99!
      url: jdbc:mysql://127.0.0.1:3306/datamgrsys?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
      username: root
      password: 931022zz.
      initial-size: 5
      max-active: 100
      min-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis:
  mapper-locations: classpath:com/zjw/datamgrsys/dao/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zjw.datamgrsys.pojo  # 注意：对应实体类的路径
logging:
  level:
    com:
      zjw:
        datamgrsys:
          dao: debug